### ISSUE TITLE
Show stripped trunks in creative menu?

### ISSUE THREAD

**Issue by sbrl** [minefaco/chisel_tree#12]
When building in creative, it would be very nice to have the ability to select the stripped trunks directly in the creative inventory, instead of them being hidden.

**Comment by minefaco** [comment]
i don't know how to do that without show the nodes in survival too, if you know how to do you can do a PR or tell me and i can do.

**Comment by sbrl** [comment]
Using the `Settings` class you can determine if `creative_mode` is enabled or not:

https://minetest.gitlab.io/minetest/class-reference/#settings

....but if they were visible in survival too, this would open the potential for showing help on how to obtain them right?

**Comment by sbrl** [comment]
Right, but if I  modify my local copy, then it would diverge from your upstream version here, making merging new changes difficult.
