### ISSUE TITLE
optional moretrees dependency 

### ISSUE THREAD

**Issue by wsor4035** [minefaco/chisel_tree#3]
add a optional dependency on moretrees with stripped textures for its nodes.

why moretrees? because is one of the most common tree mods on servers and sp worlds in addition to default trees

**Comment by minefaco** [comment]
i'm working on it.

**Comment by minefaco** [comment]
i made all textures for moretrees, uploading. now i need to code.

**Comment by wsor4035** [comment]
semi offtopic for this issue, but didn't want to open another one
maybe the texture for stripped acacia could be toned down?, it seems so stark redish, maybe make it a bit more like center of the default acacia node.

on the topic of this issue, once this support is added, are you planing any other features for this mod?

**Comment by minefaco** [comment]
-acacia's texture updated. 

-maybe add suport for moreblocks and allows the bark procesing to get paper

**Comment by wsor4035** [comment]
once moretrees support is added, i will most likely add this to a server

**Comment by minefaco** [comment]
moretrees stripped trunks are registered, just need to make it work with axe and easily add other axes.

**Comment by minefaco** [comment]
Finally, moretrees supported :+1:
