### ISSUE TITLE
no bark in creative

### ISSUE THREAD

**Issue by wsor4035** [minefaco/chisel_tree#4]
I noticed in the code you have a commented out if for doing so, wondering why you think it is wrong?
you could do it by privs as you have done,
check if the world is set to creative mode
or make your own setting for enabling/disabling the bark

**Comment by wsor4035** [comment]
continuation of #2

**Comment by minefaco** [comment]
"check if the world is set to creative mode" <- i mean this is the right way, but i don't know how to get the "creative_mode =true" variable from world.mt

**Comment by wsor4035** [comment]
https://github.com/minetest/minetest_game/blob/master/mods/map/init.lua#L14
https://github.com/minetest/minetest_game/blob/master/mods/binoculars/init.lua#L14
2 examples

**Comment by wsor4035** [comment]
shall I PR it?

**Comment by minefaco** [comment]
Added. :dancers:
